// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClp12baWJoMaSqIu5zklCnWGM38ykCPjQ',
    appId: '1:668578245744:web:23b728b06d05a9af95d8b5',
    messagingSenderId: '668578245744',
    projectId: 'random-a89fd',
    authDomain: 'random-a89fd.firebaseapp.com',
    storageBucket: 'random-a89fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbodZ0Oo9JKQ_olTK5krbvSxL1YM71UYI',
    appId: '1:668578245744:android:11d96b32ceeda22895d8b5',
    messagingSenderId: '668578245744',
    projectId: 'random-a89fd',
    storageBucket: 'random-a89fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArFtnktpQP24vFA91vLMgHBsCz0pUjWYA',
    appId: '1:668578245744:ios:67b1bdf1530a35d295d8b5',
    messagingSenderId: '668578245744',
    projectId: 'random-a89fd',
    storageBucket: 'random-a89fd.appspot.com',
    iosBundleId: 'com.example.untitled',
  );
}
